version: "3.8"

services:
  db:
    image: postgres:15
    container_name: taskmaster-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmaster
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  server:
    build: ./server
    container_name: taskmaster-server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/taskmaster"
    ports:
      - "4000:4000"

  client:
    build: ./client
    container_name: taskmaster-client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
